---
# tasks file for dotfiles

- name: Install required packages
  dnf:
    name:
      - git
      - stow
      - xclip
    state: present
  become: yes

- name: Clone dotfiles repo
  git:
    repo: git@github.com:jaredhocutt/dotfiles.git
    dest: ~/.dotfiles
    update: yes
    accept_hostkey: yes

- include_tasks: enable.yml
  loop: "{{ dotfiles_enabled }}"
